### ISSUE TITLE
Decoding Error when running Ganache 2.0.0-beta.1 on linux

### ISSUE THREAD

**Issue by boorich** [ConsenSys-archive/ganache-ui#1060]
Deployed this contract: zeppelin-solidity/contracts/token/ERC20/MintableToken.sol while running Parity in the back.

PLATFORM: linux
GANACHE VERSION: 2.0.0-beta.1

EXCEPTION:
```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at TruffleContractDecoder.<anonymous> (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:91:36)
    at Generator.next (<anonymous>)
    at fulfilled (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by seesemichaelj** [comment]
Hey @empea-careercriminal! Thanks for giving the beta a shot and for reporting the issue! I'll try to reproduce this on my end; thanks for the details. I'll let you know if I have any questions.

**Comment by seesemichaelj** [comment]
@empea-careercriminal I can't reproduce your issue. This what my contract looks like:
```
pragma solidity ^0.4.24;

import 'openzeppelin-solidity/contracts/token/ERC20/ERC20Mintable.sol';

contract MyToken is ERC20Mintable {
  constructor() ERC20Mintable() public {
  }
}
```

Both deploying and decoding (inspecting the contract via the Contracts tab) work for me.

Can you give me a link to the repo you're using? Also can you give me more details of what you mean by "running Parity in the back"? For example, what port is Parity running and what port is Ganache running? Running Parity should have no effect however.

Thanks!

**Comment by davidmurdoch** [comment]
This may be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Can you let me know if you have any issues or if this update doesn't solve the issue for you?

**Comment by srinivasmangipudi** [comment]
Is not solved. I am getting the same problems. So even simple transaction is throwing out of gas exception. I feel the two are related. How come the Ganache mac desktop app is not able to decode some contracts, when they are compiling fine by solidity compiler.
