### ISSUE TITLE
Decoding Error when running Ganache 2.1.0 on linux

### ISSUE THREAD

**Issue by lancekrogers** [ConsenSys-archive/ganache-ui#1418]
PLATFORM: linux
GANACHE VERSION: 2.1.0

EXCEPTION:
```
TypeError: Cannot read property 'id' of undefined
    at new TruffleContractDecoder (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:65:41)
    at Object.forContract (/node_modules/truffle-decoder/dist/interface/index.js:20:12)
    at Object.getContractState (/src/truffle-integration/decode.js:13:34)
    at process.<anonymous> (/src/truffle-integration/index.js:77:33)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

I get this error when viewing contracts compiled with vyper.  Solidity contracts do not have this issue

**Comment by davidmurdoch** [comment]
@haltman-at Is there anything we can do here?

**Comment by haltman-at** [comment]
Hm.  Well, I'm intending to mostly get rid of decoder exceptions in Truffle 5.1, but, as for a solution that doesn't require waiting for that...

Well, I guess my answer here depends on what sort of answer you're looking for.  The decoder won't work on Vyper contracts, no question there.  You could catch the exception and then provide the rest of the information (bytecode, balance, nonce) manually.

Or I could try modifying the decoder so that it doesn't throw an exception and just returns the `variables` part of the state as `undefined` or something?  You'd have to be prepared for that too, of course.  Or I could have it throw an exception but at a different, more conveniently-timed stage of the process?  IDK.

But yeah -- ultimately there are various approaches we can take here to the "prevent Ganache from crashing, display what information we can" problem, and I figure it's basically up to you as to which one is appropriate.  We can't decode the variables for Vyper contracts though; that's just not happening anytime soon.
