### ISSUE TITLE
Decoding Error when running Ganache 2.5.4 on win32

### ISSUE THREAD

**Issue by este78** [ConsenSys-archive/ganache-ui#3106]
PLATFORM: win32
GANACHE VERSION: 2.5.4

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 1963$ of contract$ RugbyDAUToken (ID 539)
    at C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\@truffle\decoder\lib\allocate\storage.ts:181:13
    at Array.map (<anonymous>)
    at allocateContract (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\@truffle\decoder\lib\allocate\storage.ts:178:59)
    at Object.getStorageAllocations (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\@truffle\decoder\lib\allocate\storage.ts:23:19)
    at TruffleContractDecoder.<anonymous> (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\@truffle\decoder\lib\interface\contract-decoder.ts:237:39)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\@truffle\decoder\dist\interface\contract-decoder.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by abdella206** [comment]
I had the same issue I am guessing you have window 11 installed so that may be the reason. This is the fix I found to work download the beta version https://github.com/trufflesuite/ganache-ui/releases/tag/v2.6.0-beta.3 it works
