### ISSUE TITLE
System Error when running Ganache 2.5.4 on win32

### ISSUE THREAD

**Issue by NonameDevil** [ConsenSys-archive/ganache-ui#5428]
It happens when I executed eth_getLogs. Several times eth_getLogs passed but with no result, just freezing the script, but on 10th occasion it has crashed completely.

PLATFORM: win32
GANACHE VERSION: 2.5.4

EXCEPTION:
```
Error: Incompatible EIP155-based V 0 and chain id 1. See the second parameter of the Transaction constructor to set the chain id.
    at Transaction._validateV (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\node_modules\ethereumjs-tx\src\transaction.ts:370:13)
    at Transaction.set [as v] (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\node_modules\ethereumjs-tx\src\transaction.ts:387:16)
    at C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\lib\utils\transaction.js:116:23
    at Array.forEach (<anonymous>)
    at initData (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\lib\utils\transaction.js:110:18)
    at new Transaction (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\lib\utils\transaction.js:168:5)
    at Function.fromJSON (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\lib\utils\transaction.js:228:16)
    at C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\lib\forking\forked_blockchain.js:384:21
    at Array.forEach (<anonymous>)
    at Object.callback (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\lib\forking\forked_blockchain.js:382:31)
    at sendTxCallback (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\node_modules\web3-core-method\src\index.js:664:29)
    at onJsonrpcResult (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\node_modules\web3-core-requestmanager\src\index.js:179:9)
    at C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\lib\forking\forked_blockchain.js:136:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by jeffsmale90** [comment]
Thanks for raising the issue! In v2.7.0 we upgraded the underlying ganache simulator, which I believe sound resolve this issue. Can you please try >= 2.7.0 and see if that fixes this?

Thanks!

**Comment by NonameDevil** [comment]
It works after upgrade with Ganache UI (v2.7.0). But same error happens when I use ganache-cli.

**Comment by jeffsmale90** [comment]
That's great news - `ganache-cli` has been deprecated, and is now just `ganache` - try `npm install -g ganache@latest`, and just start Ganache with `ganache` going forward, and that should resolve the issue.

LMK if this doesn't help and we can look further.

Cheers!
