### ISSUE TITLE
System Error when running Ganache 2.5.4 on linux

### ISSUE THREAD

**Issue by halienm** [ConsenSys-archive/ganache-ui#5451]
PLATFORM: linux
GANACHE VERSION: 2.5.4

EXCEPTION:
```
Error: Process exited with code 1
    at ChildProcess.done (/node_modules/promisify-child-process/index.js:64:19)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

**Comment by jeffsmale90** [comment]
Can you please try this will the latest release? https://github.com/trufflesuite/ganache-ui/releases/tag/v2.7.1

v2.7.0 introduced Ganache v7 which should resolve a large number of issues related to the ethereum simulation.
