### ISSUE TITLE
System Error when running Ganache 2.5.4 on win32

### ISSUE THREAD

**Issue by BondeYash** [ConsenSys-archive/ganache-ui#5473]
PLATFORM: win32
GANACHE VERSION: 2.5.4

EXCEPTION:
```
Error: Callback was already called.
    at C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\node_modules\async\internal\onlyOnce.js:9:32
    at C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\node_modules\async\internal\map.js:29:13
    at C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\node_modules\web3-provider-engine\index.js:170:9
    at C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\node_modules\async\internal\once.js:12:16
    at replenish (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\node_modules\async\internal\eachOfLimit.js:61:25)
    at C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\node_modules\async\internal\eachOfLimit.js:71:9
    at eachLimit (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\node_modules\async\eachLimit.js:43:36)
    at C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\node_modules\async\internal\doLimit.js:9:16
    at end (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\node_modules\web3-provider-engine\index.js:147:5)
    at next (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\node_modules\web3-provider-engine\index.js:138:9)
    at Web3ProviderEngine._handleAsync (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\node_modules\web3-provider-engine\index.js:123:3)
    at C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\node_modules\async\internal\map.js:27:9
    at eachOfArrayLike (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\node_modules\async\eachOf.js:65:9)
    at exports.default (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\node_modules\async\eachOf.js:9:5)
    at _asyncMap (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\node_modules\async\internal\map.js:25:5)
    at C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\node_modules\async\internal\doParallel.js:20:16
```

**Comment by jeffsmale90** [comment]
Thanks for opening this issue!

Can you please try to reproduce this with the latest release? We made some significant upgrades in v2.7.0 which addressed a lot of the underlying emulator issues. Feel free to close the issue if it's resolved.

https://github.com/trufflesuite/ganache-ui/releases
