### ISSUE TITLE
System Error when running Ganache 2.7.1 on win32

### ISSUE THREAD

**Issue by juliustago** [ConsenSys-archive/ganache-ui#5494]
PLATFORM: win32
GANACHE VERSION: 2.7.1

EXCEPTION:
```
Error: Command failed: powershell.exe Get-AppxPackage -Name Ganache
Get-AppxPackage : This service cannot be started in Safe Mode
This service cannot be started in Safe Mode
At line:1 char:1
+ Get-AppxPackage -Name Ganache
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AppxPackage], Exception
    + FullyQualifiedErrorId : System.Exception,Microsoft.Windows.Appx.PackageManager.Commands.GetAppxPackageCommand
 

    at ChildProcess.exithandler (child_process.js:317:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

**Comment by juliustago** [comment]
Hello, am new to this, am trying to run Ganache, and there is a error that led me here
