### ISSUE TITLE
Decoding Error when running Ganache 2.7.0 on linux

### ISSUE THREAD

**Issue by NachoSC** [ConsenSys-archive/ganache-ui#5628]
Basically I am trying to see the content from a contract that does not have anything special besides that it saves the addresses from other two contracts that are being deployed first.

The migration of the contract looks like this:

var Oracle = artifacts.require("Oracle");
var SubsOracle = artifacts.require("SubsOracle");
var MyContract = artifacts.require("Customer1");

module.exports = function(deployer, network, accounts) {
    deployer.deploy(MyContract, Oracle.address, SubsOracle.address);
};

And it is done after the deployment of the other 2 contracts. 
The error comes when I try to access the contract from the Ganache GUI.

I guess not, but could it be because in that contract I am using low-level calls to the other two?

Thanks for your time. If more specific information is needed I will provide it.

PLATFORM: linux
GANACHE VERSION: 2.7.0

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 246$ of contract$ Customer1 (ID 132)
    at /tmp/.mount_ganachejPEvH/resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:181:13
    at Array.map (<anonymous>)
    at allocateContract (/tmp/.mount_ganachejPEvH/resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:178:59)
    at Object.getStorageAllocations (/tmp/.mount_ganachejPEvH/resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:23:19)
    at TruffleContractDecoder.<anonymous> (/tmp/.mount_ganachejPEvH/resources/static/node/node_modules/@truffle/decoder/lib/interface/contract-decoder.ts:237:39)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_ganachejPEvH/resources/static/node/node_modules/@truffle/decoder/dist/interface/contract-decoder.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by NachoSC** [comment]
Having said that, it also has inheritance from an interface which is from my own code. In case it could cause any trouble.
