### ISSUE TITLE
System Error when running Ganache 2.7.1 on win32

### ISSUE THREAD

**Issue by Gershom-Taku** [ConsenSys-archive/ganache-ui#5696]
PLATFORM: win32
GANACHE VERSION: 2.7.1

EXCEPTION:
```
Error: Command failed: powershell.exe Get-AppxPackage -Name GanacheUI -Publisher *Truffle*
'powershell.exe' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:317:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
```

**Comment by Gershom-Taku** [comment]
Blockchain and SmartContracts Projects
